//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TINFO:1,2,0,&quot;The Iron Giant: Signature Edition&quot;
        ///TINFO:1,8,0,&quot;34&quot;
        ///TINFO:1,9,0,&quot;1:29:58&quot;
        ///TINFO:1,10,0,&quot;26.3 GB&quot;
        ///TINFO:1,11,0,&quot;28281956352&quot;
        ///TINFO:1,16,0,&quot;00099.mpls&quot;
        ///TINFO:1,25,0,&quot;8&quot;
        ///TINFO:1,26,0,&quot;19,24,25,27,28,29,30,31&quot;
        ///TINFO:1,27,0,&quot;The_Iron_Giant_Signature_Edition_t01.mkv&quot;
        ///TINFO:1,28,0,&quot;eng&quot;
        ///TINFO:1,29,0,&quot;English&quot;
        ///TINFO:1,30,0,&quot;The Iron Giant: Signature Edition - 34 chapter(s) , 26.3 GB&quot;
        ///TINFO:1,31,6120,&quot;&lt;b&gt;Title information&lt;/b&gt;&lt;br&gt;&quot;
        ///TINFO:1,33,0,&quot;0&quot;
        ///SINFO:1,0,1,6201,&quot;Video&quot;
        ///SINFO:1,0,5,0,&quot;V [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TheIronGiant_title1 {
            get {
                return ResourceManager.GetString("TheIronGiant_title1", resourceCulture);
            }
        }
    }
}
