//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatchMKV.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\MakeMKV")]
        public string MakeMKVPath {
            get {
                return ((string)(this["MakeMKVPath"]));
            }
            set {
                this["MakeMKVPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AnalyzeSourcesAutomatically {
            get {
                return ((bool)(this["AnalyzeSourcesAutomatically"]));
            }
            set {
                this["AnalyzeSourcesAutomatically"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ConvertSourcesAutomatically {
            get {
                return ((bool)(this["ConvertSourcesAutomatically"]));
            }
            set {
                this["ConvertSourcesAutomatically"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultOutputFolder {
            get {
                return ((string)(this["DefaultOutputFolder"]));
            }
            set {
                this["DefaultOutputFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("archive")]
        public string DefaultSourceAction {
            get {
                return ((string)(this["DefaultSourceAction"]));
            }
            set {
                this["DefaultSourceAction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ArchiveFolder {
            get {
                return ((string)(this["ArchiveFolder"]));
            }
            set {
                this["ArchiveFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ScanOnStart {
            get {
                return ((bool)(this["ScanOnStart"]));
            }
            set {
                this["ScanOnStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ScanOnStartPath {
            get {
                return ((string)(this["ScanOnStartPath"]));
            }
            set {
                this["ScanOnStartPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WindowStartX {
            get {
                return ((int)(this["WindowStartX"]));
            }
            set {
                this["WindowStartX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WindowStartY {
            get {
                return ((int)(this["WindowStartY"]));
            }
            set {
                this["WindowStartY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WindowStartWidth {
            get {
                return ((int)(this["WindowStartWidth"]));
            }
            set {
                this["WindowStartWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WindowStartHeight {
            get {
                return ((int)(this["WindowStartHeight"]));
            }
            set {
                this["WindowStartHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WindowStartMaximized {
            get {
                return ((bool)(this["WindowStartMaximized"]));
            }
            set {
                this["WindowStartMaximized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OutputOverwrite {
            get {
                return ((bool)(this["OutputOverwrite"]));
            }
            set {
                this["OutputOverwrite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SubtitleCompression {
            get {
                return ((bool)(this["SubtitleCompression"]));
            }
            set {
                this["SubtitleCompression"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("raw")]
        public string AudioLPCMContainer {
            get {
                return ((string)(this["AudioLPCMContainer"]));
            }
            set {
                this["AudioLPCMContainer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("good")]
        public string AudioFLACCompression {
            get {
                return ((string)(this["AudioFLACCompression"]));
            }
            set {
                this["AudioFLACCompression"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("copy")]
        public string AudioTranscodeDefault {
            get {
                return ((string)(this["AudioTranscodeDefault"]));
            }
            set {
                this["AudioTranscodeDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AudioTranscodeCodecs {
            get {
                return ((string)(this["AudioTranscodeCodecs"]));
            }
            set {
                this["AudioTranscodeCodecs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\MKVToolNix")]
        public string MKVToolNixPath {
            get {
                return ((string)(this["MKVToolNixPath"]));
            }
            set {
                this["MKVToolNixPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ScanRecentFolders {
            get {
                return ((string)(this["ScanRecentFolders"]));
            }
            set {
                this["ScanRecentFolders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public byte RecentFoldersMax {
            get {
                return ((byte)(this["RecentFoldersMax"]));
            }
            set {
                this["RecentFoldersMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DefaultAudioIncludeAll {
            get {
                return ((bool)(this["DefaultAudioIncludeAll"]));
            }
            set {
                this["DefaultAudioIncludeAll"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DefaultAudioIncludeQuailty {
            get {
                return ((bool)(this["DefaultAudioIncludeQuailty"]));
            }
            set {
                this["DefaultAudioIncludeQuailty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DefaultAudioIncludeNonFavourite {
            get {
                return ((bool)(this["DefaultAudioIncludeNonFavourite"]));
            }
            set {
                this["DefaultAudioIncludeNonFavourite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DefaultAudioIncludeFirst {
            get {
                return ((bool)(this["DefaultAudioIncludeFirst"]));
            }
            set {
                this["DefaultAudioIncludeFirst"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public byte DefaultAudioLimit {
            get {
                return ((byte)(this["DefaultAudioLimit"]));
            }
            set {
                this["DefaultAudioLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte DefaultAudioMainCore {
            get {
                return ((byte)(this["DefaultAudioMainCore"]));
            }
            set {
                this["DefaultAudioMainCore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public byte DefaultAudioOrder {
            get {
                return ((byte)(this["DefaultAudioOrder"]));
            }
            set {
                this["DefaultAudioOrder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DefaultSubtitleIncludeAll {
            get {
                return ((bool)(this["DefaultSubtitleIncludeAll"]));
            }
            set {
                this["DefaultSubtitleIncludeAll"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public byte DefaultSubtitleLimit {
            get {
                return ((byte)(this["DefaultSubtitleLimit"]));
            }
            set {
                this["DefaultSubtitleLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public byte DefaultSubtitleOrder {
            get {
                return ((byte)(this["DefaultSubtitleOrder"]));
            }
            set {
                this["DefaultSubtitleOrder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("eng")]
        public string FavouriteLanguages {
            get {
                return ((string)(this["FavouriteLanguages"]));
            }
            set {
                this["FavouriteLanguages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public byte DefaultSubtitleTrack {
            get {
                return ((byte)(this["DefaultSubtitleTrack"]));
            }
            set {
                this["DefaultSubtitleTrack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ScanSimultaneously {
            get {
                return ((bool)(this["ScanSimultaneously"]));
            }
            set {
                this["ScanSimultaneously"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public ushort ScanDrivePollInterval {
            get {
                return ((ushort)(this["ScanDrivePollInterval"]));
            }
            set {
                this["ScanDrivePollInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ScanDrives {
            get {
                return ((bool)(this["ScanDrives"]));
            }
            set {
                this["ScanDrives"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public ushort TitlesIgnoreLength {
            get {
                return ((ushort)(this["TitlesIgnoreLength"]));
            }
            set {
                this["TitlesIgnoreLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DefaultTitlesIgnoreMuted {
            get {
                return ((bool)(this["DefaultTitlesIgnoreMuted"]));
            }
            set {
                this["DefaultTitlesIgnoreMuted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DefaultTitlesIncludeAll {
            get {
                return ((bool)(this["DefaultTitlesIncludeAll"]));
            }
            set {
                this["DefaultTitlesIncludeAll"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public ushort DefaultTitlesIncludeWithinLength {
            get {
                return ((ushort)(this["DefaultTitlesIncludeWithinLength"]));
            }
            set {
                this["DefaultTitlesIncludeWithinLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{name-default}")]
        public string DefaultTitleName {
            get {
                return ((string)(this["DefaultTitleName"]));
            }
            set {
                this["DefaultTitleName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultTitleFilename {
            get {
                return ((string)(this["DefaultTitleFilename"]));
            }
            set {
                this["DefaultTitleFilename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RestoreSources {
            get {
                return ((bool)(this["RestoreSources"]));
            }
            set {
                this["RestoreSources"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ClearFinishedSourcesOnExit {
            get {
                return ((bool)(this["ClearFinishedSourcesOnExit"]));
            }
            set {
                this["ClearFinishedSourcesOnExit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ClearMissingSourcesOnStart {
            get {
                return ((bool)(this["ClearMissingSourcesOnStart"]));
            }
            set {
                this["ClearMissingSourcesOnStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public byte PurgeSourceState {
            get {
                return ((byte)(this["PurgeSourceState"]));
            }
            set {
                this["PurgeSourceState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2016-01-01")]
        public global::System.DateTime PurgeSourceStateLastExecuted {
            get {
                return ((global::System.DateTime)(this["PurgeSourceStateLastExecuted"]));
            }
            set {
                this["PurgeSourceStateLastExecuted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public long LastSourceSelectedID {
            get {
                return ((long)(this["LastSourceSelectedID"]));
            }
            set {
                this["LastSourceSelectedID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DefaultAudioIncludeCommentaryTracks {
            get {
                return ((bool)(this["DefaultAudioIncludeCommentaryTracks"]));
            }
            set {
                this["DefaultAudioIncludeCommentaryTracks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Commentary")]
        public string DefaultAudioCommentaryTrackName {
            get {
                return ((string)(this["DefaultAudioCommentaryTrackName"]));
            }
            set {
                this["DefaultAudioCommentaryTrackName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ErrorLogging {
            get {
                return ((bool)(this["ErrorLogging"]));
            }
            set {
                this["ErrorLogging"] = value;
            }
        }
    }
}
